---
- hosts: all
  become: true
  include_vars: "../vars.yml"
  vars:
    ###
    ### Plex
    ###
    # If you're paranoid, set permissions to "ro" so Plex won't ever be able to
    # delete your files
    docker_home: /mnt/drive2/docker
    plex_available_externally: "false"
    plex_config_directory: "{{ docker_home }}/plex/config"
    plex_logs: "{{ docker_home }}/plex/logs"
    plex_movies_directory: "/mnt/drive2/Media/Movies"
    plex_movies_permissions: "rw"
    plex_tv_directory: "/mnt/drive2/Media/TV"
    plex_tv_permissions: "rw"
    plex_photos_permissions: "rw"
    plex_podcasts_permissions: "rw"
    plex_music_directory: "/mnt/drive2/Media/Music"
    plex_music_permissions: "rw"
    plex_user_id: "0"
    plex_group_id: "0"
    plex_port: "32400"

  tasks:
  - name: Create Plex Directories
    file:
      path: "{{ item }}"
      state: directory
      # mode: 0755
    with_items:
      - "{{ plex_config_directory }}"
      - "{{ plex_logs }}"

  - name: plex Docker Container
    docker_container:
      name: plex
      image: linuxserver/plex
      pull: true
      volumes:
        - "{{ plex_config_directory }}:/config:rw"
        - "{{ plex_logs }}:/opt/plex/Library/Application Support/Plex Media Server/Logs:rw"
        - "{{ plex_movies_directory }}:/movies:{{ plex_movies_permissions }}"
        - "{{ plex_tv_directory }}:/tv:{{ plex_tv_permissions }}"
        - "{{ plex_music_directory }}:/music:{{ plex_music_permissions }}"
      network_mode: "host"
      env:
        PUID: "{{ plex_user_id }}"
        PGID: "{{ plex_group_id }}"
      restart_policy: unless-stopped
      memory: 2g