---
- hosts: all
  become: true
  vars:
  tasks:
  - name: Install required packages
    apt:
      name: apt-transport-https
      state: latest
  - name: Add jellyfin apt key
    apt_key:
      url: https://repo.jellyfin.org/jellyfin_team.gpg.key
      state: present
  - name: Add Jellyfin repo
    apt_repository:
      repo: deb [arch=arm64] https://repo.jellyfin.org/ubuntu focal main
      state: absent
  - name: Update the package index
    apt:
      update_cache: yes
  - name: Install Jellyfin
    apt:
      package: jellyfin
      state: absent
  - name: Nice jellyfin
    lineinfile:
      path: /lib/systemd/system/jellyfin.service
      insertafter: "Service"
      line: "Nice = -10"
      firstmatch: yes
      state: present
  - name: Run systemctl daemon-reload
    systemd:
      daemon_reload: yes
  - name: Enable jellyfin service
    systemd:
      name: jellyfin
      enabled: no
  - name: Manage jellyfin service
    service:
      name: jellyfin
      state: stopped